### ISSUE TITLE
some error!

### ISSUE THREAD

**Issue by andyyuan78** [mesnilgr/iclr15#3]
Alpha: 0.000002  Progress: 100.03%  Words/thread/sec: 20.90k  
real    182m22.244s
user    422m39.620s
sys     0m22.516s
../iclr15/scripts/paragraph.sh: line 16: ../liblinear-1.96/train: No such file or directory
../iclr15/scripts/paragraph.sh: line 17: ../liblinear-1.96/predict: No such file or directory
tail: cannot open ‘out.logreg’ for reading: No such file or directory
../iclr15/scripts/paragraph.sh: line 26: ../liblinear-1.96/train: No such file or directory
../iclr15/scripts/paragraph.sh: line 27: ../liblinear-1.96/predict: No such file or directory
tail: cannot open ‘out.logreg’ for reading: No such file or directory
rm: cannot remove ‘model.logreg’: No such file or directory
rm: cannot remove ‘out.logreg’: No such file or directory
Cloning into 'nbsvm'...
The authenticity of host 'github.com (192.30.252.128)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Connection closed by 192.30.252.128
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
../iclr15/scripts/nbsvm.sh: line 2: cd: nbsvm: No such file or directory
python: can't open file 'nbsvm.py': [Errno 2] No such file or directory
tail: cannot open ‘../scores/NBSVM-VALID’ for reading: No such file or directory
mv: cannot move ‘tmp’ to ‘../scores/NBSVM-VALID’: No such file or directory
python: can't open file 'nbsvm.py': [Errno 2] No such file or directory
tail: cannot open ‘../scores/NBSVM-TEST’ for reading: No such file or directory
mv: cannot move ‘tmp’ to ‘../scores/NBSVM-TEST’: No such file or directory

['RNNLM']        valid / test 83.54 / 86.16
/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py:816: UserWarning: loadtxt: Empty input file: "scores/PARAGRAPH-VALID"
  warnings.warn('loadtxt: Empty input file: "%s"' % fname)
Traceback (most recent call last):
  File "./../iclr15/scripts/combine.py", line 65, in <module>
    valid, test = load("VALID", c), load("TEST", c)
  File "./../iclr15/scripts/combine.py", line 24, in load
    data = normalize(data[:, 2] - 0.5)
IndexError: too many indices
ubgpu@ubgpu:~/github/iclr15$ 
ubgpu@ubgpu:~/github/iclr15$

**Comment by xchangcheng** [comment]
This is because the 'install_liblinear.sh' fail.
You can download liblinear-1.96 from 'https://github.com/karlstratos/minitagger' and make it as 'install_liblinear.sh'.
